### ISSUE TITLE
build error with BarcodeScanner

### ISSUE THREAD

**Issue by uuleaf** [geneanet/customCamera#95]
after 
cordova plugin add https://github.com/wildabeast/BarcodeScanner.git
when
cordova build android

**Comment by ChristopheBoucaut** [comment]
You install customCamera plugin and after bardcodeScanner ?

Can you give me the error message ?

**Comment by uuleaf** [comment]
when ever install customCamera before  barcodeScanner  or after , can not build cordova success;
i have try to install barcodeScanner alone ,build success;
install customCamera alone ,build success;
when two plugin together,build failed. 
error msg:

[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found Deleted Target File
     [aapt] Generating resource IDs...
     [aapt] warning: string 'menu_settings' has no default translation.
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\bookmark_picker_list_item.xml:17: error: Error: No resource found that matches the given name (at 'padding' with value '@dimen/half_padding'
).
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:30: error: Error: No resource found that matches the given name (at 'background' with value '@color/result_view').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:38: error: Error: No resource found that matches the given name (at 'padding' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:52: error: Error: No resource found that matches the given name (at 'layout_marginBottom' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:66: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:66: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:73: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:85: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:85: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:92: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:104: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:104: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:111: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:123: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:123: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:131: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:149: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:149: error: Error: No resource found that matches the given name (at 'textColorLink' with value '@color/result_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:158: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:158: error: Error: No resource found that matches the given name (at 'textColorLink' with value '@color/result_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:210: error: Error: No resource found that matches the given name (at 'background' with value '@color/transparent').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\capture.xml:210: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/status_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:30: error: Error: No resource found that matches the given name (at 'background' with value '@color/result_view').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:38: error: Error: No resource found that matches the given name (at 'padding' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:52: error: Error: No resource found that matches the given name (at 'layout_marginBottom' with value '@dimen/half_padding')
.
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:66: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:66: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:73: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:85: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:85: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:92: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:104: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:104: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:111: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:123: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:123: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:131: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_minor_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:149: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:149: error: Error: No resource found that matches the given name (at 'textColorLink' with value '@color/result_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:158: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/result_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:158: error: Error: No resource found that matches the given name (at 'textColorLink' with value '@color/result_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:211: error: Error: No resource found that matches the given name (at 'background' with value '@color/transparent').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-ldpi\capture.xml:211: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/status_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\encode.xml:18: error: Error: No resource found that matches the given name (at 'background' with value '@color/encode_view').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\encode.xml:37: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/contents_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\encode.xml:37: error: Error: No resource found that matches the given name (at 'paddingBottom' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\encode.xml:37: error: Error: No resource found that matches the given name (at 'paddingLeft' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\encode.xml:37: error: Error: No resource found that matches the given name (at 'paddingRight' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-land\encode.xml:17: error: Error: No resource found that matches the given name (at 'background' with value '@color/encode_view').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout-land\encode.xml:36: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/contents_text').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\help.xml:27: error: Error: No resource found that matches the given name (at 'paddingTop' with value '@dimen/half_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\history_list_item.xml:3: error: Error: No resource found that matches the given name (at 'padding' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\search_book_contents_header.xml:17: error: Error: No resource found that matches the given name (at 'paddingLeft' with value '@dimen/standar
d_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\search_book_contents_header.xml:17: error: Error: No resource found that matches the given name (at 'paddingBottom' with value '@dimen/half_
padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\search_book_contents_list_item.xml:17: error: Error: No resource found that matches the given name (at 'padding' with value '@dimen/standard
_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\search_book_contents_list_item.xml:24: error: Error: No resource found that matches the given name (at 'layout_marginRight' with value '@dim
en/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\share.xml:26: error: Error: No resource found that matches the given name (at 'padding' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\share.xml:33: error: Error: No resource found that matches the given name (at 'paddingBottom' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\share.xml:40: error: Error: No resource found that matches the given name (at 'paddingBottom' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\share.xml:47: error: Error: No resource found that matches the given name (at 'paddingBottom' with value '@dimen/standard_padding').
     [aapt]
     [aapt] D:\javaapp\libapp\platforms\android\res\layout\share.xml:67: error: Error: No resource found that matches the given name (at 'paddingBottom' with value '@dimen/standard_padding').
     [aapt]

BUILD FAILED
D:\IDE\android-sdk\tools\ant\build.xml:653: The following error occurred while executing this line:
D:\IDE\android-sdk\tools\ant\build.xml:698: null returned: 1

Total time: 1 second

D:\javaapp\libapp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "ant debug -f D:\javaapp\libapp\platforms\android\build.xml -Dout.dir=ant-build -Dgen.absolute.dir=ant-gen"
ERROR building one of the platforms: Error: D:\javaapp\libapp\platforms\android\cordova\build.bat: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: D:\javaapp\libapp\platforms\android\cordova\build.bat: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Program Files\nodejs\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)

**Comment by ChristopheBoucaut** [comment]
Thank you, I will investigate friday if I have time.
